site_name: SparkFun Qwiic Universal Auto-Detect - Examples

nav:
  - Example 1 - Thing Plus C: "ex_01_Thing_Plus_C.md"
  - Example 2 - ESP32 LittleFS: "ex_02_ESP32_LittleFS.md"
  - Example 3 - EEPROM: "ex_03_EEPROM.md"
  - Example 4 - Custom Initialization: "ex_04_Custom_Initialization.md"
  - Example 5 - Memory Leak Test: "ex_05_Memory_Leak_Test.md"
  - Example 6 - Thing Plus C Logger: "ex_06_Thing_Plus_C_Logger.md"
  - Example 7 - Thing Plus C Logger RTC: "ex_07_Thing_Plus_C_Logger_RTC.md"
  - Example 8 - Thing Plus C Logger ThingSpeak Publish: "ex_08_Thing_Plus_C_ThingSpeak.md"
  - Example 9 - Menu Memory Leak Test: "ex_09_Menu_Memory_Leak_Test.md"
