name: Compile Sketch

on:
  # - push
  - pull_request


jobs:
  update-libraries:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Branch name
        run: echo update-libraries running on branch ${GITHUB_REF##*/}

      - name: Update I2C Mux
        run: |
          cd ./src/src/
          mkdir -p I2C_MUX
          cd I2C_MUX
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_I2C_Mux_Arduino_Library/master/src/SparkFun_I2C_Mux_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_I2C_Mux_Arduino_Library/master/src/SparkFun_I2C_Mux_Arduino_Library.cpp

      - name: Update ADS122C04
        run: |
          cd ./src/src/
          mkdir -p ADS122C04
          cd ADS122C04
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library/main/src/SparkFun_ADS122C04_ADC_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library/main/src/SparkFun_ADS122C04_ADC_Arduino_Library.cpp

      - name: Update AHT20
        run: |
          cd ./src/src/
          mkdir -p AHT20
          cd AHT20
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Humidity_AHT20_Arduino_Library/main/src/SparkFun_Qwiic_Humidity_AHT20.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Humidity_AHT20_Arduino_Library/main/src/SparkFun_Qwiic_Humidity_AHT20.cpp
          # SparkFun_Qwiic_Humidity_AHT20.cpp uses #include <SparkFun_Qwiic_Humidity_AHT20.h>. We need to replace the < and > with double quotes
          sed -i 's/<SparkFun_Qwiic_Humidity_AHT20.h>/'\"'SparkFun_Qwiic_Humidity_AHT20.h'\"'/g' SparkFun_Qwiic_Humidity_AHT20.cpp

      - name: Update BME280
        run: |
          cd ./src/src/
          mkdir -p BME280
          cd BME280
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_BME280_Arduino_Library/master/src/SparkFunBME280.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_BME280_Arduino_Library/master/src/SparkFunBME280.cpp

      - name: Update LPS25HB
        run: |
          cd ./src/src/
          mkdir -p LPS25HB
          cd LPS25HB
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_LPS25HB_Arduino_Library/master/src/SparkFun_LPS25HB_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_LPS25HB_Arduino_Library/master/src/SparkFun_LPS25HB_Arduino_Library.cpp
          # SparkFun_LPS25HB_Arduino_Library.cpp uses #include <SparkFun_LPS25HB_Arduino_Library.h>. We need to replace the < and > with double quotes
          sed -i 's/<SparkFun_LPS25HB_Arduino_Library.h>/'\"'SparkFun_LPS25HB_Arduino_Library.h'\"'/g' SparkFun_LPS25HB_Arduino_Library.cpp

      - name: Update MS5637
        run: |
          cd ./src/src/
          mkdir -p MS5637
          cd MS5637
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_MS5637_Arduino_Library/master/src/SparkFun_MS5637_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_MS5637_Arduino_Library/master/src/SparkFun_MS5637_Arduino_Library.cpp

      - name: Update NAU7802
        run: |
          cd ./src/src/
          mkdir -p NAU7802
          cd NAU7802
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library/master/src/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library/master/src/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library.cpp

      - name: Update UBLOX_GNSS
        run: |
          cd ./src/src/
          mkdir -p UBLOX_GNSS
          cd UBLOX_GNSS
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/main/src/SparkFun_u-blox_GNSS_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/main/src/SparkFun_u-blox_GNSS_Arduino_Library.cpp
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/main/src/u-blox_config_keys.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/main/src/u-blox_structs.h

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:        
          message: 'update-libraries'
        
  compile-sketch:

    needs: update-libraries

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        board:
          # ESP32
          # https://github.com/espressif/arduino-esp32/blob/master/boards.txt
          - fqbn: esp32:esp32:esp32
            platforms: |
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Branch name
        run: echo compile-sketch running on branch ${GITHUB_REF##*/}

      - name: Compile Sketch
        uses: arduino/compile-sketches@v1
        with:
          platforms: ${{ matrix.board.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: ./
          sketch-paths: |
            - examples/Example1_ESP32_Thing_Plus_C
          enable-warnings-report: true
          enable-deltas-report: true
          # verbose: true

    # outputs:
    #   report-artifact-name: ${{ steps.report-artifact-name.outputs.report-artifact-name }}

