name: Compile Sketch

on:
  # - push
  - pull_request


jobs:
  update-libraries:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Branch name
        run: echo update-libraries running on branch ${GITHUB_REF##*/}

      - name: Update I2C Mux
        run: |
          cd ./src/src/
          mkdir -p I2C_MUX
          cd I2C_MUX
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_I2C_Mux_Arduino_Library/master/src/SparkFun_I2C_Mux_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_I2C_Mux_Arduino_Library/master/src/SparkFun_I2C_Mux_Arduino_Library.cpp

      - name: Update ADS122C04
        run: |
          cd ./src/src/
          mkdir -p ADS122C04
          cd ADS122C04
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library/main/src/SparkFun_ADS122C04_ADC_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_ADS122C04_ADC_Arduino_Library/main/src/SparkFun_ADS122C04_ADC_Arduino_Library.cpp

      - name: Update AHT20
        run: |
          cd ./src/src/
          mkdir -p AHT20
          cd AHT20
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Humidity_AHT20_Arduino_Library/main/src/SparkFun_Qwiic_Humidity_AHT20.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Humidity_AHT20_Arduino_Library/main/src/SparkFun_Qwiic_Humidity_AHT20.cpp
          # SparkFun_Qwiic_Humidity_AHT20.cpp uses #include <SparkFun_Qwiic_Humidity_AHT20.h>. We need to replace the < and > with double quotes
          sed -i 's/<SparkFun_Qwiic_Humidity_AHT20.h>/'\"'SparkFun_Qwiic_Humidity_AHT20.h'\"'/g' SparkFun_Qwiic_Humidity_AHT20.cpp

      - name: Update BME280
        run: |
          cd ./src/src/
          mkdir -p BME280
          cd BME280
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_BME280_Arduino_Library/master/src/SparkFunBME280.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_BME280_Arduino_Library/master/src/SparkFunBME280.cpp

      - name: Update CCS811
        run: |
          cd ./src/src/
          mkdir -p CCS811
          cd CCS811
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_CCS811_Arduino_Library/master/src/SparkFunCCS811.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_CCS811_Arduino_Library/master/src/SparkFunCCS811.cpp

      - name: Update LPS25HB
        run: |
          cd ./src/src/
          mkdir -p LPS25HB
          cd LPS25HB
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_LPS25HB_Arduino_Library/master/src/SparkFun_LPS25HB_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_LPS25HB_Arduino_Library/master/src/SparkFun_LPS25HB_Arduino_Library.cpp
          # SparkFun_LPS25HB_Arduino_Library.cpp uses #include <SparkFun_LPS25HB_Arduino_Library.h>. We need to replace the < and > with double quotes
          sed -i 's/<SparkFun_LPS25HB_Arduino_Library.h>/'\"'SparkFun_LPS25HB_Arduino_Library.h'\"'/g' SparkFun_LPS25HB_Arduino_Library.cpp

      - name: Update MAX1704X
        run: |
          cd ./src/src/
          mkdir -p MAX1704X
          cd MAX1704X
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library/main/src/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library/main/src/SparkFun_MAX1704x_Fuel_Gauge_Arduino_Library.cpp

      - name: Update MCP9600
        run: |
          cd ./src/src/
          mkdir -p MCP9600
          cd MCP9600
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_MCP9600_Arduino_Library/master/src/SparkFun_MCP9600.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_MCP9600_Arduino_Library/master/src/SparkFun_MCP9600.cpp
          # SparkFun_MCP9600.cpp uses #include <SparkFun_MCP9600.h>. We need to replace the < and > with double quotes
          sed -i 's/<SparkFun_MCP9600.h>/'\"'SparkFun_MCP9600.h'\"'/g' SparkFun_MCP9600.cpp

      - name: Update MICROPRESSURE
        run: |
          cd ./src/src/
          mkdir -p MICROPRESSURE
          cd MICROPRESSURE
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_MicroPressure_Arduino_Library/main/src/SparkFun_MicroPressure.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_MicroPressure_Arduino_Library/main/src/SparkFun_MicroPressure.cpp

      - name: Update MS5637
        run: |
          cd ./src/src/
          mkdir -p MS5637
          cd MS5637
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_MS5637_Arduino_Library/master/src/SparkFun_MS5637_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_MS5637_Arduino_Library/master/src/SparkFun_MS5637_Arduino_Library.cpp

      - name: Update MS8607
        run: |
          cd ./src/src/
          mkdir -p MS8607
          cd MS8607
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_PHT_MS8607_Arduino_Library/master/src/SparkFun_PHT_MS8607_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_PHT_MS8607_Arduino_Library/master/src/SparkFun_PHT_MS8607_Arduino_Library.cpp
    
      - name: Update NAU7802
        run: |
          cd ./src/src/
          mkdir -p NAU7802
          cd NAU7802
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library/master/src/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library/master/src/SparkFun_Qwiic_Scale_NAU7802_Arduino_Library.cpp

      - name: Update QWIICBUTTON
        run: |
          cd ./src/src/
          mkdir -p QWIICBUTTON
          cd QWIICBUTTON
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Button_Arduino_Library/master/src/SparkFun_Qwiic_Button.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Button_Arduino_Library/master/src/SparkFun_Qwiic_Button.cpp
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_Qwiic_Button_Arduino_Library/master/src/registers.h
          # SparkFun_Qwiic_Button.cpp uses #include <SparkFun_Qwiic_Button.h>. We need to replace the < and > with double quotes
          sed -i 's/<SparkFun_Qwiic_Button.h>/'\"'SparkFun_Qwiic_Button.h'\"'/g' SparkFun_Qwiic_Button.cpp

      - name: Update SCD30
        run: |
          cd ./src/src/
          mkdir -p SCD30
          cd SCD30
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SCD30_Arduino_Library/main/src/SparkFun_SCD30_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SCD30_Arduino_Library/main/src/SparkFun_SCD30_Arduino_Library.cpp

      - name: Update SCD4X
        run: |
          cd ./src/src/
          mkdir -p SCD4X
          cd SCD4X
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SCD4x_Arduino_Library/main/src/SparkFun_SCD4x_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SCD4x_Arduino_Library/main/src/SparkFun_SCD4x_Arduino_Library.cpp

      - name: Update SDP3X
        run: |
          cd ./src/src/
          mkdir -p SDP3X
          cd SDP3X
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SDP3x_Arduino_Library/main/src/SparkFun_SDP3x_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SDP3x_Arduino_Library/main/src/SparkFun_SDP3x_Arduino_Library.cpp

      - name: Update SGP30
        run: |
          cd ./src/src/
          mkdir -p SGP30
          cd SGP30
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SGP30_Arduino_Library/main/src/SparkFun_SGP30_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SGP30_Arduino_Library/main/src/SparkFun_SGP30_Arduino_Library.cpp

      - name: Update SGP40
        run: |
          cd ./src/src/
          mkdir -p SGP40
          cd SGP40
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SGP40_Arduino_Library/main/src/SparkFun_SGP40_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SGP40_Arduino_Library/main/src/SparkFun_SGP40_Arduino_Library.cpp
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SGP40_Arduino_Library/main/src/sensirion_arch_config.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SGP40_Arduino_Library/main/src/sensirion_voc_algorithm.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SGP40_Arduino_Library/main/src/sensirion_voc_algorithm.c

      - name: Update SHTC3
        run: |
          cd ./src/src/
          mkdir -p SHTC3
          cd SHTC3
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SHTC3_Arduino_Library/master/src/SparkFun_SHTC3.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_SHTC3_Arduino_Library/master/src/SparkFun_SHTC3.cpp

      - name: Update STC31
        run: |
          cd ./src/src/
          mkdir -p STC31
          cd STC31
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_STC3x_Arduino_Library/main/src/SparkFun_STC3x_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_STC3x_Arduino_Library/main/src/SparkFun_STC3x_Arduino_Library.cpp

      - name: Update TMP117
        run: |
          cd ./src/src/
          mkdir -p TMP117
          cd TMP117
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_TMP117_Arduino_Library/master/src/SparkFun_TMP117.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_TMP117_Arduino_Library/master/src/SparkFun_TMP117.cpp
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_TMP117_Arduino_Library/master/src/SparkFun_TMP117_Registers.h

      - name: Update UBLOX_GNSS
        run: |
          cd ./src/src/
          mkdir -p UBLOX_GNSS
          cd UBLOX_GNSS
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/main/src/SparkFun_u-blox_GNSS_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/main/src/SparkFun_u-blox_GNSS_Arduino_Library.cpp
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/main/src/u-blox_config_keys.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/main/src/u-blox_structs.h

      - name: Update VCNL4040
        run: |
          cd ./src/src/
          mkdir -p VCNL4040
          cd VCNL4040
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VCNL4040_Arduino_Library/master/src/SparkFun_VCNL4040_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VCNL4040_Arduino_Library/master/src/SparkFun_VCNL4040_Arduino_Library.cpp

      - name: Update VEML6075
        run: |
          cd ./src/src/
          mkdir -p VEML6075
          cd VEML6075
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VEML6075_Arduino_Library/master/src/SparkFun_VEML6075_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VEML6075_Arduino_Library/master/src/SparkFun_VEML6075_Arduino_Library.cpp
          # SparkFun_VEML6075_Arduino_Library.cpp uses #include <SparkFun_VEML6075_Arduino_Library.h>. We need to replace the < and > with double quotes
          sed -i 's/<SparkFun_VEML6075_Arduino_Library.h>/'\"'SparkFun_VEML6075_Arduino_Library.h'\"'/g' SparkFun_VEML6075_Arduino_Library.cpp

      - name: Update VEML7700
        run: |
          cd ./src/src/
          mkdir -p VEML7700
          cd VEML7700
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VEML7700_Arduino_Library/main/src/SparkFun_VEML7700_Arduino_Library.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VEML7700_Arduino_Library/main/src/SparkFun_VEML7700_Arduino_Library.cpp

      - name: Update VL53L1X
        run: |
          cd ./src/src/
          mkdir -p VL53L1X
          cd VL53L1X
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/master/src/SparkFun_VL53L1X.cpp
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/master/src/SparkFun_VL53L1X.cpp
          mkdir -p st_src
          cd st_src
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/master/src/st_src/ComponentObject.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/master/src/st_src/vl53l1_error_codes.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/master/src/st_src/vl53l1x_class.h
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/master/src/st_src/vl53l1x_class.cpp
          curl -O https://raw.githubusercontent.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/master/src/st_src/RangeSensor.h
          sed -i 's/<st_src\/ComponentObject.h>/'\"'ComponentObject.h'\"'/g' RangeSensor.h

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:        
          message: 'update-libraries'
        
  compile-sketch:

    needs: update-libraries

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        board:
          # ESP32
          # https://github.com/espressif/arduino-esp32/blob/master/boards.txt
          - fqbn: esp32:esp32:esp32
            platforms: |
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

          # ESP32-S2
          # https://github.com/espressif/arduino-esp32/blob/master/boards.txt
          - fqbn: esp32:esp32:esp32s2
            platforms: |
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

          # ESP32-C3
          # https://github.com/espressif/arduino-esp32/blob/master/boards.txt
          - fqbn: esp32:esp32:esp32c3
            platforms: |
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

          # ESP8266
          # https://github.com/esp8266/Arduino/blob/master/boards.txt
          - fqbn: esp8266:esp8266:thingdev
            platforms: |
              - name: esp8266:esp8266
                source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json

          # Artemis / Apollo3
          # https://github.com/sparkfun/Arduino_Apollo3/blob/main/boards.txt
          - fqbn: SparkFun:apollo3:sfe_artemis_atp
            platforms: |
              - name: SparkFun:apollo3
                source-url: https://raw.githubusercontent.com/sparkfun/Arduino_Apollo3/master/package_sparkfun_apollo3_index.json

          # SAMD21
          # https://github.com/arduino/ArduinoCore-samd/blob/master/boards.txt
          - fqbn: arduino:samd:mkr1000
            platforms: |
              - name: arduino:samd
                # source-url: https://downloads.arduino.cc/packages/package_index.json

          # Nano BLE 33 / nRF52840
          # https://github.com/arduino/ArduinoCore-mbed/blob/master/boards.txt
          - fqbn: arduino:mbed:nano33ble
            platforms: |
              - name: arduino:mbed
                # source-url: https://downloads.arduino.cc/packages/package_index.json

          # RP2040
          # https://github.com/arduino/ArduinoCore-mbed/blob/master/boards.txt
          - fqbn: rp2040:rp2040:sparkfun_promicrorp2040
            platforms: |
              - name: rp2040:rp2040
                source-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

          # STM32
          # https://github.com/arduino/ArduinoCore-mbed/blob/master/boards.txt
          - fqbn: STMicroelectronics:stm32:GenF4
            platforms: |
              - name: STMicroelectronics:stm32
                source-url: https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Branch name
        run: echo compile-sketch running on branch ${GITHUB_REF##*/}

      - name: Compile Sketch
        uses: arduino/compile-sketches@v1
        with:
          platforms: ${{ matrix.board.platforms }}
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: ./
          sketch-paths: |
            - examples/Example1_ESP32_Thing_Plus_C
          enable-warnings-report: true
          enable-deltas-report: true
          # verbose: true

    # outputs:
    #   report-artifact-name: ${{ steps.report-artifact-name.outputs.report-artifact-name }}

